### ISSUE TITLE
ERROR:  Error installing oxidized:         net-telnet requires Ruby version >= 2.3.0.

### ISSUE THREAD

**Issue by rygumcmxci** [ytti/oxidized#1602]
Seems that I am having the same issue as:

https://github.com/ytti/oxidized/issues/1472

OS: CentOS 7 

I have removed ruby 2.1.2 and installed 2.4.2 using rvm, but it is still giving me the same problem. 

Any thoughts on resolving this dependency issue?

**Comment by rygumcmxci** [comment]
Fixed issue

**Comment by rdpettigrew** [comment]
> Fixed issue

How were you able to fix this?  I am doing a fresh install of oxidized on centos 7 today and hitting the same error.

**Comment by thymikon** [comment]
same error here

**Comment by jonathanbaird** [comment]
I am also having this issue, I've installed Ruby 2.3.0 but still face the same issue. Running ruby --version shows the below.

ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

**Comment by rygumcmxci** [comment]
> > Fixed issue
> 
> How were you able to fix this? I am doing a fresh install of oxidized on centos 7 today and hitting the same error.

Hi, so if you have ran into this problem during install I am going to assume that you have already installed the gems. 

What you will have to do is list the gems using "**gem list**", this will list out the gems that you have installed. In my case I had two versions of "net-telnet" installed. 

So, I had to uninstall the wrong version of the gem using "**gem uninstall net_telnet --version $VERSION**" and rebooted my server (this part was probably not necessary but since it wasn't in production yet I figured, why not) and after that it worked. 

Hope this helps.
